name: Windows x64 Bitcoin Build

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
          mingw-w64-x86_64-toolchain
          base-devel
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-qt5
          mingw-w64-x86_64-libevent
          mingw-w64-x86_64-openssl
          autoconf
          automake-wrapper
          libtool
          pkg-config
          make
          git
          wget
          tar
          unzip
          zip

    - name: Build Berkeley DB (patched for Windows)
      shell: msys2 {0}
      run: |
        cd /tmp
        curl -L -o db-4.8.30.NC.tar.gz https://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
        tar -xzf db-4.8.30.NC.tar.gz
        cd db-4.8.30.NC/build_unix
        ../dist/configure --enable-mingw --enable-cxx --disable-shared --with-mutex=windows --with-pic --prefix=/mingw64
        make -j$(nproc)
        make install

    - name: Build Bitcoin
      shell: msys2 {0}
      run: |
        cd $GITHUB_WORKSPACE
        ./autogen.sh
        export CPPFLAGS="-I/mingw64/include"
        export LDFLAGS="-L/mingw64/lib"
        ./configure --prefix=/mingw64 --disable-tests --disable-bench
        make -j$(nproc)

    - name: Package executables
      shell: msys2 {0}
      run: |
        mkdir -p artifacts
        cp src/bitcoind.exe artifacts/ || true
        cp src/qt/bitcoin-qt.exe artifacts/ || true
        cd artifacts
        zip bitcoin-build.zip *.exe
        ls -lh

    - name: Upload artifact (zip)
      uses: actions/upload-artifact@v4
      with:
        name: bitcoin-x64-build
        path: artifacts/bitcoin-build.zip
