name: Windows x64 Bitcoin Build

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
          mingw-w64-x86_64-toolchain
          base-devel
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-qt5
          mingw-w64-x86_64-libevent
          mingw-w64-x86_64-openssl
          autoconf
          automake-wrapper
          libtool
          pkg-config
          make
          git
          wget
          tar
          unzip

    - name: Build Berkeley DB
      shell: msys2 {0}
      run: |
        cd /tmp
        wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
        tar -xzf db-4.8.30.NC.tar.gz
        cd db-4.8.30.NC/build_unix
        ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=/mingw64
        make -j4
        make install

    - name: Build Bitcoin
      shell: msys2 {0}
      run: |
        cd $GITHUB_WORKSPACE
        ./autogen.sh
        ./configure --prefix=/mingw64 --disable-tests --disable-bench
        make -j4

    - name: Collect executables
      shell: msys2 {0}
      run: |
        mkdir artifacts
        cp src/bitcoind.exe artifacts/ || true
        cp src/qt/bitcoin-qt.exe artifacts/ || true
        ls -la artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bitcoin-exe
        path: artifacts/*
